config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'playlists#index'
  devise_for :users
  # devise_for :users, skip: [:registrations] # this 'skip' prevents people from freating new acconuts
  resources :playlist_poses
  resources :playlists
  resources :poses, only: %i[index new create edit update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
# frozen_string_literal: true

class Playlist < ApplicationRecord
  SPEAK_TIME_BUFFER_SECONDS = 2
  PLAYLIST_COMPLETE_AUDIO_FILE = 'chime.wav'

  belongs_to :user
  has_many :playlist_poses, dependent: :destroy
  has_many :poses, through: :playlist_poses

  accepts_nested_attributes_for :playlist_poses,
                                reject_if: :all_blank, # at least 1 ingredient should be present
                                allow_destroy: true # allows user to delete ingredient via checkbox

  validates :name,
            presence: true

  validates :hold_time,
            presence: true,
            numericality: { greater_than: 0 }

  def duration_in_minutes
    duration_in_seconds / 60
  end

  def duration_in_seconds
    qty = poses.count
    time_per_track = hold_time + speak_time_buffer
    time_per_track * qty
  end

  def speak_time_buffer
    SPEAK_TIME_BUFFER_SECONDS
  end

  def tracks_for_js
    tracks = playlist_poses.order(:sequence_number).map do |pose|
      { id: pose.id, audio_file: pose.audio_file }
    end
    tracks << { id: 0, audio_file: PLAYLIST_COMPLETE_AUDIO_FILE }
    tracks.to_json.html_safe # rubocop:disable Rails/OutputSafety
  end
end

app/models/playlist_pose.rb
# frozen_string_literal: true

class PlaylistPose < ApplicationRecord
  belongs_to :playlist
  belongs_to :pose

  delegate :audio_file, to: :pose
  validates :sequence_number,
            uniqueness: { scope: :playlist_id }
end

app/models/pose.rb
# frozen_string_literal: true

class Pose < ApplicationRecord
  belongs_to :user
  has_many :playlist_poses, dependent: :destroy
  has_many :playlists, through: :playlist_poses

  validates :name,
            :audio_file,
            :image_file,
            presence: true

  scope :by_name, -> { order(name: 'ASC') }
  scope :public_poses, -> { where(admin_only: false) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :playlists, dependent: :destroy
  has_many :poses, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  def require_admin
    return if current_user_admin?

    sign_out current_user
    redirect_to new_user_session_path, alert: 'Must be Admin to access this area'
  end

  def current_user_admin?
    current_user&.admin?
  end
  helper_method :current_user_admin?
end

app/controllers/playlists_controller.rb
# frozen_string_literal: true

class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[show edit update destroy]

  def index
    @playlists = current_user.playlists.order(:name)
  end

  def show
  end

  def new
    @playlist = current_user.playlists.new
    i = 1
    15.times do
      @playlist.playlist_poses.build(sequence_number: i)
      i += 1
    end
  end

  def edit
    @playlist.playlist_poses.order(:sequence_number)
    3.times { @playlist.playlist_poses.build }
  end

  def create
    @playlist = current_user.playlists.new(playlist_params)
    @playlist.playlist_poses = @playlist.playlist_poses.reject { |pose| pose.pose_id.nil? }

    if @playlist.save
      redirect_to @playlist, notice: 'Playlist was successfully created.'
    else
      render :new
    end
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to @playlist, notice: 'Playlist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @playlist.destroy
    redirect_to playlists_url, notice: 'Playlist was successfully destroyed.'
  end

  private

  def set_playlist
    @playlist = current_user.playlists.find(params[:id])
  end

  def playlist_params
    params.require(:playlist).permit(:name,
                                     :hold_time,
                                     :user_id,
                                     playlist_poses_attributes: %i[
                                       id
                                       sequence_number
                                       pose_id
                                       _destroy
                                     ])
  end
end

app/controllers/poses_controller.rb
# frozen_string_literal: true

class PosesController < ApplicationController
  before_action :set_pose, only: %i[show edit update destroy]
  before_action :require_admin

  def index
    @poses = current_user.poses.by_name
  end

  def show
  end

  def new
    @pose = current_user.poses.new
  end

  def edit
  end

  def create
    @pose = current_user.poses.new(pose_params)

    if @pose.save
      redirect_to poses_url, notice: 'Pose was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pose.update(pose_params)
      redirect_to poses_url, notice: 'Pose was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pose.destroy
    redirect_to poses_url, notice: 'Pose was successfully destroyed.'
  end

  private

  def set_pose
    @pose = current_user.poses.find(params[:id])
  end

  def pose_params
    params.require(:pose).permit(:name, :audio_file, :image_file, :user_id, :admin_only)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def page_title
    if content_for?(:title)
      content_for(:title)
    else
      'YogaPlaylists'
    end
  end

  def bootstrap_flash_class(type)
    case type
    when 'alert' then 'warning'
    when 'error' then 'danger'
    when 'notice' then 'success'
    else
      'info'
    end
  end
end

app/helpers/poses_helper.rb
# frozen_string_literal: true

module PosesHelper
  def form_poses(user)
    user.admin? ? Pose.by_name : Pose.public_poses.by_name
  end

  def display_pose_image(pose)
    # file = Rails.application.assets.find_asset(pose.image_file) ? pose.image_file : 'placeholder.png'
    # image_tag file
    image_tag pose.image_file
  rescue StandardError
    image_tag 'image_missing.png'
  end
end

app/helpers/styles_helper.rb
# frozen_string_literal: true

module StylesHelper
  def button_classes(style = 'primary')
    "btn btn-sm btn-#{style}"
  end
end

app/helpers/symbols_helper.rb
# frozen_string_literal: true

module SymbolsHelper
  def chevron_right
    '&rsaquo;'.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= raw page_title %></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class='container'>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

app/views/playlist_poses/_form_fields.html.erb
<td><%= f_playlist_pose.text_field :sequence_number, class: 'form-control input--small' %></td>
<td>
  <%= f_playlist_pose.collection_select :pose_id, form_poses(current_user), :id, :name, { prompt: "-- Select a Pose --" }, class: 'form-control' %>
</td>

<td><%= f_playlist_pose.check_box :_destroy if f_playlist_pose.object.persisted? %></td>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist, local: true) do |form| %>
  <%= render 'shared/errors', object: playlist %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label 'Hold Time (sec)' %>
    <%= form.number_field :hold_time, class: 'form-control' %>
  </div>

  <table class="table table-playlist_poses">
    <thead>
      <tr>
        <th width="10%">Sequence Number</th>
        <th>Pose</th>
        <th width="10%">Delete?</th>
      </tr>
    </thead>
    <tbody>
      <%= form.fields_for :playlist_poses do |f_playlist_pose| %>
      <tr> <%= render 'playlist_poses/form_fields', f_playlist_pose: f_playlist_pose %> </tr>
      <% end %>
    </tbody>
  </table>

  <div class="actions">
    <%= form.submit class: button_classes %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<div class='mb-3'>
  <%= link_to 'Cancel', playlists_path, class: button_classes('secondary right') %>
  <%= link_to 'Home', root_path %> <%= chevron_right %>
  <%= link_to 'Playlists', playlists_path %> <%= chevron_right %>
  <%= link_to @playlist.name, playlist_path(@playlist) %> <%= chevron_right %>
  Edit
</div>

<h2><%= @playlist.name %></h2>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<%= link_to 'New Playlist', new_playlist_path, class: button_classes('primary right') %>

<h1>Playlists</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= link_to playlist.name, playlist %></td>
        <td><%= playlist.duration_in_minutes %> min</td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/playlists/new.html.erb
<div class='mb-3'>
  <%= link_to 'Cancel', playlists_path, class: button_classes('secondary right') %>
  <%= link_to 'Home', root_path %> <%= chevron_right %>
  <%= link_to 'Playlists', playlists_path %> <%= chevron_right %>
  New
</div>

<h2>New Playlist</h2>

<%= render 'form', playlist: @playlist %>

app/views/playlists/show.html.erb
<%= link_to 'Back', playlists_path, class: button_classes('secondary right ml-2') %>
<%= link_to 'Edit', edit_playlist_path(@playlist), class: button_classes('primary right ml-2') %>

<h1>
  <%= @playlist.name %>
  <%#= link_to 'Stop', "", class: 'btn btn-sm btn-danger' %>
</h1>

<p>
  <strong>Hold Time:</strong> <%= @playlist.hold_time %> seconds<br>
  <strong>Duration:</strong> <%= @playlist.duration_in_minutes %> minutes
</p>

<table class='table'  id='table'>
  <thead>
    <tr>
      <th>Order</th>
      <th>Pose</th>
      <th><%= link_to '<i class="fas fa-play-circle"></i> Play'.html_safe, '#', id: 'button-play', class: button_classes('info right') %></th>
    </tr>
  </thead>

  <tbody>
    <% @playlist.playlist_poses.order(:sequence_number).each do |playlist_pose| %>
      <tr id="<%= playlist_pose.id %>">
        <td><span class='sequence-number'><%= playlist_pose.sequence_number %></span></td>
        <td><%= link_to display_pose_image(playlist_pose.pose), playlist_pose.pose, class: 'thumbnail' %></td>
        <td><%= playlist_pose.pose.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= javascript_include_tag 'playlists'%>
<script type="text/javascript">
  playTracks(<%= @playlist.hold_time %>, <%= @playlist.speak_time_buffer %>, <%= @playlist.tracks_for_js %>);
</script>

app/views/poses/_form.html.erb
<%= form_with(model: pose, local: true) do |form| %>
  <%= render 'shared/errors', object: pose %>

  <div class='form-group row'>
    <%= form.label :name, class: 'col-sm-2 col-form-label' %>
    <div class='col-sm-10'>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group row'>
    <%= form.label :audio_file, class: 'col-sm-2 col-form-label'  %>
    <div class='col-sm-10'>
      <%= form.text_field :audio_file, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group row'>
    <%= form.label :image_file, class: 'col-sm-2 col-form-label'  %>
    <div class='col-sm-10'>
      <%= form.text_field :image_file, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group row'>
    <%= form.label :admin_only, class: 'col-sm-2 col-form-label'  %>
    <div class='col-sm-10'>
      <%= form.check_box :admin_only, class: 'form-control' %>
    </div>
  </div>

  <div class='actions mt-3'>
    <%= form.submit class: button_classes %>
  </div>
<% end %>

app/views/poses/edit.html.erb
<div class='mb-3'>
  <%= link_to 'Cancel', poses_path, class: button_classes('secondary right') %>
  <%= link_to 'Home', root_path %> <%= chevron_right %>
  <%= link_to 'Poses', poses_path %> <%= chevron_right %>
  Edit
</div>

<h2><%= @pose.name %></h2>

<center class='mb-2'><%= display_pose_image(@pose) %></center>

<%= render 'form', pose: @pose %>

<hr>
<td><%= link_to 'Delete', @pose, class: button_classes('danger'), method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/poses/index.html.erb
<%= link_to 'New Pose', new_pose_path, class: button_classes('primary right') %>
<h1>Poses</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Play</th>
    </tr>
  </thead>

  <tbody>
    <% @poses.each do |pose| %>
      <tr>
        <td><%= link_to display_pose_image(pose), edit_pose_path(pose), class: 'thumbnail' %></td>
        <td>
          <%= link_to pose.name, edit_pose_path(pose) %>
        </td>
        <td>
          <%= audio_tag "/audio_files/#{pose.audio_file}", class: "audio-play" %>
          <span id="<%= pose.audio_file %>" class="btn btn-sm btn-info audioButton">Play</span>
          <%#= link_to 'Play', '', id: pose.audio_file, class: 'btn btn-sm btn-primary audioButton' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function () {
    $(".audioButton").on("click", function() {
      let trackFileName = event.target.id;
      const track = new Audio(`/audio_files/${trackFileName}`);
      console.log(track)
      track.play().catch(e => {
        console.log(e);
      });
    });
  });
</script>

app/views/poses/new.html.erb
<div class='mb-3'>
  <%= link_to 'Cancel', poses_path, class: button_classes('secondary right') %>
  <%= link_to 'Home', root_path %> <%= chevron_right %>
  <%= link_to 'Poses', poses_path %> <%= chevron_right %>
  New
</div>

<h2>New Pose</h2>

<%= render 'form', pose: @pose %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id='error_explanation'>
    <h2><%= pluralize(object.errors.count, 'error') %> prohibited this object from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= bootstrap_flash_class(type) %> fadein">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden=true>&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class='navbar navbar-expand-sm navbar-light bg-light mb-2'>
  <%= link_to 'YogaPlaylist', root_url, class: 'navbar-brand' %>
  <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
    <span class='navbar-toggler-icon'></span>
  </button>

  <div class='collapse navbar-collapse' id='navbarSupportedContent'>
    <ul class='navbar-nav mr-auto'>
      <% if current_user %>
        <%= render 'shared/session_nav' %>
      <% else %>
        <li class="nav-item"><%= link_to 'Log In', new_user_session_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_session_nav.html.erb
<li class='nav-item'><%= link_to 'Playlists', playlists_path, class: 'nav-link' %></li>
<% if current_user_admin? %>
  <li class='nav-item'><%= link_to 'Poses', poses_path, class: 'nav-link' %></li>
<% end %>

<li class='nav-item dropdown'>
  <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
      <%= current_user.email %>
  </a>
  <div class='dropdown-menu' aria-labelledby='navbarDropdown'>
    <%#= link_to 'Edit My Profile', edit_user_registration_path, class: 'dropdown-item' %>
    <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
  </div>
</li>